# Site settings
title: NIOD Digitale Onderzoeksgids Koloniale Collecties
author:
  name: Wiebe Reints
  email: w.reints@niod.knaw.nl
description: "Test website voor het publiceren van zoekhulpen."

# Build settings
remote_theme: just-the-docs
